import { useMemo, useState } from 'react'
import { DataTable, type TableColumn } from '../ui/DataTable'
import { DetailModal } from '../ui/DetailModal'
import { Pagination } from '../ui/Pagination'
import { SearchInput } from '../ui/SearchInput'
import { StatusBadge } from '../ui/StatusBadge'
import type { EntityStatus } from '../../models/operational'

type Field = { name: string; label: string; placeholder: string }
export type ResourceConfig<T extends { id: string }> = { title: string; description: string; singular: string; items: T[]; columns: TableColumn<T>[]; searchText: (item: T) => string; details: (item: T) => { label: string; value: string }[]; status: (item: T) => EntityStatus; fields: Field[]; create: (values: Record<string, string>) => T }
const perPage = 5
export function ResourceScreen<T extends { id: string }>({ config }: { config: ResourceConfig<T> }) {
  const [items, setItems] = useState(config.items); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Todos'); const [selected, setSelected] = useState<T | null>(null); const [showForm, setShowForm] = useState(false); const [page, setPage] = useState(1); const [form, setForm] = useState<Record<string, string>>({})
  const filtered = useMemo(() => items.filter((item) => config.searchText(item).toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (filter === 'Todos' || config.status(item) === filter)), [config, filter, items, query])
  const totalPages = Math.max(1, Math.ceil(filtered.length / perPage)); const visible = filtered.slice((page - 1) * perPage, page * perPage)
  const createItem = () => { const item = config.create(form); setItems((current) => [item, ...current]); setForm({}); setShowForm(false); setPage(1) }
  return <section className="resource-screen"><div className="resource-metrics"><div><span>Total</span><b>{items.length}</b></div><div><span>Ativos no filtro</span><b>{filtered.length}</b></div><div><span>Exigem atenção</span><b>{items.filter((item) => ['Crítica', 'Atrasada', 'Em andamento'].includes(config.status(item))).length}</b></div></div><div className="resource-toolbar"><SearchInput value={query} onChange={(value) => { setQuery(value); setPage(1) }} placeholder={`Buscar ${config.title.toLocaleLowerCase()}...`} /><label className="filter-select"><span>Filtro</span><select value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1) }}><option>Todos</option>{Array.from(new Set(items.map(config.status))).map((status) => <option key={status}>{status}</option>)}</select></label><button className="primary-button" onClick={() => setShowForm(true)}>+ Novo {config.singular}</button></div><article className="panel resource-panel"><div className="panel__header"><div><h2>{config.title}</h2><p>{config.description}</p></div><span className="result-count">{filtered.length} resultados</span></div><DataTable columns={config.columns} items={visible} onSelect={setSelected} /><Pagination page={page} total={totalPages} onChange={setPage} /></article>{selected && <DetailModal title={config.singular} onClose={() => setSelected(null)}><div className="detail-grid">{config.details(selected).map((detail) => <div key={detail.label}><span>{detail.label}</span><b>{detail.value}</b></div>)}</div><div className="detail-status"><span>Status</span><StatusBadge status={config.status(selected)} /></div></DetailModal>}{showForm && <DetailModal title={`Novo ${config.singular}`} onClose={() => setShowForm(false)}><form className="resource-form" onSubmit={(event) => { event.preventDefault(); createItem() }}>{config.fields.map((field) => <label key={field.name}>{field.label}<input required placeholder={field.placeholder} value={form[field.name] ?? ''} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} /></label>)}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => setShowForm(false)}>Cancelar</button><button className="primary-button">Salvar localmente</button></div></form></DetailModal>}</section>
}
