import { useState } from 'react'
import { Header } from './components/layout/Header'
import { Sidebar } from './components/layout/Sidebar'
import { MetricCard } from './components/ui/MetricCard'
import { StatusBadge } from './components/ui/StatusBadge'
import { navigationItems, serviceOrders } from './data/dashboard'

function Dashboard() { return <><section className="metric-grid" aria-label="Indicadores operacionais"><MetricCard label="Ordens abertas" value="24" helper="6 para hoje" trend="warning" /><MetricCard label="Em atendimento" value="08" helper="Equipe em campo" trend="positive" /><MetricCard label="Preventivas do mês" value="87%" helper="Meta: 90%" trend="positive" /><MetricCard label="Equipamentos críticos" value="03" helper="Exigem atenção" trend="warning" /></section><section className="dashboard-grid"><article className="panel panel--orders"><div className="panel__header"><div><h2>Ordens de serviço de hoje</h2><p>Acompanhe a agenda operacional em tempo real.</p></div><button className="text-button">Ver todas →</button></div><div className="orders-table" role="table" aria-label="Ordens de serviço de hoje"><div className="orders-table__header" role="row"><span>ORDEM</span><span>CLIENTE / LOCAL</span><span>HORÁRIO</span><span>STATUS</span></div>{serviceOrders.map((order) => <div className="orders-table__row" role="row" key={order.id}><b>{order.id}</b><span><strong>{order.client}</strong><small>{order.location}</small></span><span>{order.time}</span><StatusBadge status={order.status} /></div>)}</div></article><article className="panel panel--focus"><div className="panel__header"><div><h2>Foco da semana</h2><p>Prioridades para a operação.</p></div></div><div className="focus-card"><span className="focus-card__icon">↻</span><div><b>Preventivas pendentes</b><p>12 equipamentos estão próximos da data de revisão.</p><button className="text-button">Abrir manutenção →</button></div></div><div className="progress-label"><span>Conformidade preventiva</span><b>87%</b></div><div className="progress"><span /></div><div className="mini-stats"><div><b>36</b><span>Concluídas</span></div><div><b>05</b><span>Reagendadas</span></div></div></article></section></> }
function ComingSoon({ title }: { title: string }) { return <section className="empty-state"><span>◫</span><h2>{title}</h2><p>Este módulo já está preparado na navegação e será desenvolvido nas próximas sprints.</p></section> }
function App() { const [activeItem, setActiveItem] = useState('Dashboard'); const [isMenuOpen, setMenuOpen] = useState(false); return <div className="app-shell"><Sidebar items={navigationItems} activeItem={activeItem} onNavigate={setActiveItem} isOpen={isMenuOpen} onClose={() => setMenuOpen(false)} /><div className="app-content"><Header onMenuClick={() => setMenuOpen(true)} /><main><section className="page-heading"><div><p className="eyebrow">ACC CLIMATIZAÇÃO</p><h1>{activeItem}</h1><span>Controle simples para operações que não podem parar.</span></div><button className="primary-button">+ Nova ordem de serviço</button></section>{activeItem === 'Dashboard' ? <Dashboard /> : <ComingSoon title={activeItem} />}</main></div></div> }
export default App
