import { useState } from 'react'
import { Header } from './components/layout/Header'
import { Sidebar } from './components/layout/Sidebar'
import { ResourceScreen } from './components/operations/ResourceScreen'
import { MetricCard } from './components/ui/MetricCard'
import { StatusBadge } from './components/ui/StatusBadge'
import { clientConfig, equipmentConfig, locationConfig, maintenanceConfig, orderConfig } from './config/resource-configs'
import { navigationItems } from './data/dashboard'
import { clients, equipment, locations, maintenanceItems, serviceOrders } from './mocks/operational'
const clientName = (id: string) => clients.find((item) => item.id === id)?.name ?? '—'; const locationName = (id: string) => locations.find((item) => item.id === id)?.name ?? '—'
function Dashboard({ onNavigate }: { onNavigate: (item: string) => void }) { const activeOrders = serviceOrders.filter((order) => order.status !== 'Concluída'); return <><section className="metric-grid"><MetricCard label="Ordens abertas" value={String(activeOrders.length)} helper="Agenda de hoje" trend="warning" /><MetricCard label="Em atendimento" value={String(serviceOrders.filter((order) => order.status === 'Em andamento').length)} helper="Equipe em campo" trend="positive" /><MetricCard label="Equipamentos críticos" value={String(equipment.filter((item) => item.status === 'Crítica').length)} helper="Exigem atenção" trend="warning" /><MetricCard label="Preventivas em dia" value={`${Math.round((maintenanceItems.filter((item) => item.status === 'Em dia').length / maintenanceItems.length) * 100)}%`} helper="Plano de manutenção" trend="positive" /></section><section className="dashboard-grid"><article className="panel panel--orders"><div className="panel__header"><div><h2>Ordens de serviço de hoje</h2><p>Acompanhe a agenda operacional em tempo real.</p></div><button className="text-button" onClick={() => onNavigate('Ordens de Serviço')}>Ver todas →</button></div><div className="orders-table" role="table"><div className="orders-table__header" role="row"><span>ORDEM</span><span>CLIENTE / LOCAL</span><span>HORÁRIO</span><span>STATUS</span></div>{serviceOrders.map((order) => <div className="orders-table__row" role="row" key={order.id}><b>{order.code}</b><span><strong>{clientName(order.clientId)}</strong><small>{locationName(order.locationId)}</small></span><span>{order.scheduledFor.split('· ')[1]}</span><StatusBadge status={order.status} /></div>)}</div></article><article className="panel panel--focus"><div className="panel__header"><div><h2>Foco da semana</h2><p>Prioridades para a operação.</p></div></div><div className="focus-card"><span className="focus-card__icon">↻</span><div><b>Preventivas pendentes</b><p>{maintenanceItems.filter((item) => item.status !== 'Em dia').length} equipamentos precisam de acompanhamento.</p><button className="text-button" onClick={() => onNavigate('Manutenção')}>Abrir manutenção →</button></div></div><div className="progress-label"><span>Conformidade preventiva</span><b>87%</b></div><div className="progress"><span /></div><div className="mini-stats"><div><b>{clients.length}</b><span>Clientes ativos</span></div><div><b>{locations.length}</b><span>Locais atendidos</span></div></div></article></section></> }
function ComingSoon({ title }: { title: string }) { return <section className="empty-state"><span>◫</span><h2>{title}</h2><p>Este módulo permanece preparado na navegação e será desenvolvido nas próximas sprints.</p></section> }
function App() { const [activeItem, setActiveItem] = useState('Dashboard'); const [isMenuOpen, setMenuOpen] = useState(false); let content = <ComingSoon title={activeItem} />; if (activeItem === 'Dashboard') content = <Dashboard onNavigate={setActiveItem} />; if (activeItem === 'Clientes') content = <ResourceScreen config={clientConfig} />; if (activeItem === 'Locais') content = <ResourceScreen config={locationConfig} />; if (activeItem === 'Equipamentos') content = <ResourceScreen config={equipmentConfig} />; if (activeItem === 'Ordens de Serviço') content = <ResourceScreen config={orderConfig} />; if (activeItem === 'Manutenção') content = <ResourceScreen config={maintenanceConfig} />; return <div className="app-shell"><Sidebar items={navigationItems} activeItem={activeItem} onNavigate={setActiveItem} isOpen={isMenuOpen} onClose={() => setMenuOpen(false)} /><div className="app-content"><Header onMenuClick={() => setMenuOpen(true)} /><main><section className="page-heading"><div><p className="eyebrow">ACC CLIMATIZAÇÃO · NÚCLEO OPERACIONAL</p><h1>{activeItem}</h1><span>Controle simples para operações que não podem parar.</span></div>{activeItem === 'Dashboard' && <button className="primary-button" onClick={() => setActiveItem('Ordens de Serviço')}>+ Nova ordem de serviço</button>}</section>{content}</main></div></div> }
export default App
